### ISSUE TITLE
Mentioning "Hyperorg" and comparing it to similar tools 

### ISSUE THREAD

**Issue by buhtz** [sachac/emacs-news#1]
Dear Sascha,
I found your [emacs-news](https://sachachua.com/blog/category/emacs-news/).

Might it be possible to take a look at [Hyperorg](https://codeberg.org/buhtz/hyperorg). I am the other and released the first stable version yesterday. It is a org-2-html converter written in Python targeting Zettelkasten and personal wiki as the main use case.

Beside mention it in your news section I am very interested in your opinion as an experience Emacs user especially in comparing it to similar tools.

Thanks in advance
Christian

**Comment by sachac** [comment]
Hello, Christian! There's some discussion of Hyperorg at <https://www.reddit.com/r/planetemacs/comments/129rg6r/hyperorg_hyperorg_converts_orgfiles_and/> , which is linked in the [2023-04-03 Emacs News](https://sachachua.com/blog/2023/04/2023-04-03-emacs-news/). I'll include a link to the new release. Happy to link to any more recent discussions or posts if you come across them or start them! =) I don't have much computer time at the moment, so I might not be able to dig into it much myself, but I'm glad people are playing around with this sort of stuff. Good luck and have fun!
